import dedent from 'dedent-js'
const { start, updateContent, buildFluentTypeModule } = require('../src')

test('Should match the types definitions for vanilla target', async () => {
  const fixturePtFirstVersion = dedent`
    hello = Olá { $firstName }
    how-are-you = Como você está?
    bye = Tchau
  `
  const fixtureJp = dedent`
    hello = こんにちは{ $lastName }
    how-are-you = お元気ですか？
  `

  start([
    { path: 'pt.ftl', content: fixturePtFirstVersion },
    { path: 'jp.ftl', content: fixtureJp },
  ])

  const fluentTypeModuleFirstVersion = buildFluentTypeModule('vanilla')
  expect(fluentTypeModuleFirstVersion).toBe(dedent`
    // This file is automatically generated.
    // Please do not change this file!

    type Message<T extends MessagesKey> = {
      id: T
      value: T
      attributes: Record<string, T>
    }

    import { FluentBundle, FluentArgument } from '@fluent/bundle'

    declare global {
      interface FluentBundleTyped extends FluentBundle {
        getMessage<T extends MessagesKey>(id: T): Message<T>
        formatPattern: <T extends MessagesKey>(...args: PatternArguments<T>) => string
      }
    }

    type MessagesKey = 'hello' |
    'how-are-you' |
    'bye'
    type PatternArguments<T extends MessagesKey> = (
      T extends 'hello'
      ? [T, { 'firstName': FluentArgument,'lastName': FluentArgument }]:
    T extends 'how-are-you'
      ? [T]:
    T extends 'bye'
      ? [T]
      : never
    )
  `)

  const fixturePtSecondVersion = dedent`
    hello = Olá { $firstName }
    how-are-you = Como você está?
  `
  updateContent({ path: 'pt.ftl', content: fixturePtSecondVersion })

  const fluentTypeModuleSecondVersion = buildFluentTypeModule('vanilla')
  expect(fluentTypeModuleSecondVersion).toBe(dedent`
    // This file is automatically generated.
    // Please do not change this file!

    type Message<T extends MessagesKey> = {
      id: T
      value: T
      attributes: Record<string, T>
    }

    import { FluentBundle, FluentArgument } from '@fluent/bundle'

    declare global {
      interface FluentBundleTyped extends FluentBundle {
        getMessage<T extends MessagesKey>(id: T): Message<T>
        formatPattern: <T extends MessagesKey>(...args: PatternArguments<T>) => string
      }
    }

    type MessagesKey = 'hello' |
    'how-are-you'
    type PatternArguments<T extends MessagesKey> = (
      T extends 'hello'
      ? [T, { 'firstName': FluentArgument,'lastName': FluentArgument }]:
    T extends 'how-are-you'
      ? [T]
      : never
    )
  `)
})

test('Should match the types definitions for react-18next target', async () => {
  const fixturePtFirstVersion = dedent`
    hello = Olá { $firstName }
    how-are-you = Como você está?
    bye = Tchau
  `
  const fixtureJp = dedent`
    hello = こんにちは{ $lastName }
    how-are-you = お元気ですか？
  `

  start([
    { path: 'pt.ftl', content: fixturePtFirstVersion },
    { path: 'jp.ftl', content: fixtureJp },
  ])

  const fluentTypeModuleFirstVersion = buildFluentTypeModule('react-18next')
  expect(fluentTypeModuleFirstVersion).toBe(dedent`
    // This file is automatically generated.
    // Please do not change this file!

    type Message<T extends MessagesKey> = {
      id: T
      value: T
      attributes: Record<string, T>
    }

    import { FluentArgument } from '@fluent/bundle'
    import { TransProps } from 'react-i18next'

    declare module 'react-i18next' {
      interface UseTranslationResponsePatched extends Omit<UseTranslationResponse, 't'> {
        t: <T extends MessagesKey>(...args: PatternArguments<T>) => string
      }

      function useTranslation(ns?: Namespace, options?: UseTranslationOptions): UseTranslationResponsePatched
    }

    type MessagesKey = 'hello' |
    'how-are-you' |
    'bye'
    type PatternArguments<T extends MessagesKey> = (
      T extends 'hello'
      ? [T, { 'firstName': FluentArgument,'lastName': FluentArgument }]:
    T extends 'how-are-you'
      ? [T]:
    T extends 'bye'
      ? [T]
      : never
    )
  `)

  const fixturePtSecondVersion = dedent`
    hello = Olá { $firstName }
    how-are-you = Como você está?
  `
  updateContent({ path: 'pt.ftl', content: fixturePtSecondVersion })

  const fluentTypeModuleSecondVersion = buildFluentTypeModule('react-18next')
  expect(fluentTypeModuleSecondVersion).toBe(dedent`
    // This file is automatically generated.
    // Please do not change this file!

    type Message<T extends MessagesKey> = {
      id: T
      value: T
      attributes: Record<string, T>
    }

    import { FluentArgument } from '@fluent/bundle'
    import { TransProps } from 'react-i18next'

    declare module 'react-i18next' {
      interface UseTranslationResponsePatched extends Omit<UseTranslationResponse, 't'> {
        t: <T extends MessagesKey>(...args: PatternArguments<T>) => string
      }

      function useTranslation(ns?: Namespace, options?: UseTranslationOptions): UseTranslationResponsePatched
    }

    type MessagesKey = 'hello' |
    'how-are-you'
    type PatternArguments<T extends MessagesKey> = (
      T extends 'hello'
      ? [T, { 'firstName': FluentArgument,'lastName': FluentArgument }]:
    T extends 'how-are-you'
      ? [T]
      : never
    )
  `)
})
