// This file is automatically generated.
// Please do not change this file!

type Message0<T extends MessagesKey0> = {
  id: T
  value: T
  attributes: Record<string, T>
}

import { FluentBundle, FluentVariable } from '@fluent/bundle'

declare global {
  interface FluentBundleTyped extends FluentBundle {
    getMessage<T extends MessagesKey0>(id: T): Message0<T>
formatPattern<T extends MessagesKey0>(...args: PatternArguments0<T>): string
  }
}

type MessagesKey0 = 'hello' |
'how-are-you' |
'bye'
type PatternArguments0<T extends MessagesKey0> = (
  T extends 'hello'
  ? [T, { 'firstName': FluentVariable,'lastName': FluentVariable }]:
T extends 'how-are-you'
  ? [T]:
T extends 'bye'
  ? [T]
  : never
)