// This file is automatically generated.
// Please do not change this file!

type Message0<T extends MessagesKey0> = {
  id: T
  value: T
  attributes: Record<string, T>
}
type Message1<T extends MessagesKey1> = {
  id: T
  value: T
  attributes: Record<string, T>
}
type Message2<T extends MessagesKey2> = {
  id: T
  value: T
  attributes: Record<string, T>
}


import { FluentBundle, FluentVariable } from '@fluent/bundle'

declare global {
  interface FluentBundleTyped extends FluentBundle {
  
getMessage<T extends MessagesKey0>(id: T): Message0<T>
  formatPattern<T extends MessagesKey0>(...args: PatternArguments0<T>) : string


getMessage<T extends MessagesKey1>(id: T): Message1<T>
  formatPattern<T extends MessagesKey1>(...args: PatternArguments1<T>) : string


getMessage<T extends MessagesKey2>(id: T): Message2<T>
  formatPattern<T extends MessagesKey2>(...args: PatternArguments2<T>) : string

      
  }
}


type MessagesKey0 = 'hello' |
'how-are-you' |
'bye' |
't1' |
't2' |
't3' |
't4' |
't5' |
't6' |
't7' |
't8' |
't9' |
't10' |
't11' |
't12' |
't13' |
't14' |
't15' |
't16' |
't17' |
't18' |
't19' |
't20' |
't21' |
't22'
type MessagesKey1 = 't23' |
't24' |
't25' |
't26' |
't27' |
't28' |
't29' |
't30' |
't31' |
't32' |
't33' |
't34' |
't35' |
't36' |
't37' |
't38' |
't39' |
't40' |
't41' |
't42' |
't43' |
't44' |
't45' |
't46' |
't47'
type MessagesKey2 = 't48' |
't49' |
't50' |
't51' |
't52' |
't53'
type PatternArguments0<T extends MessagesKey0> = ( T extends 'hello'
  ? [T, { 'firstName': FluentVariable,'lastName': FluentVariable }]:
T extends 'how-are-you'
  ? [T]:
T extends 'bye'
  ? [T]:
T extends 't1'
  ? [T]:
T extends 't2'
  ? [T]:
T extends 't3'
  ? [T]:
T extends 't4'
  ? [T]:
T extends 't5'
  ? [T]:
T extends 't6'
  ? [T]:
T extends 't7'
  ? [T]:
T extends 't8'
  ? [T]:
T extends 't9'
  ? [T]:
T extends 't10'
  ? [T]:
T extends 't11'
  ? [T]:
T extends 't12'
  ? [T]:
T extends 't13'
  ? [T]:
T extends 't14'
  ? [T]:
T extends 't15'
  ? [T]:
T extends 't16'
  ? [T]:
T extends 't17'
  ? [T]:
T extends 't18'
  ? [T]:
T extends 't19'
  ? [T]:
T extends 't20'
  ? [T]:
T extends 't21'
  ? [T]:
T extends 't22'
  ? [T]: never
)
type PatternArguments1<T extends MessagesKey1> = ( T extends 't23'
  ? [T]:
T extends 't24'
  ? [T]:
T extends 't25'
  ? [T]:
T extends 't26'
  ? [T]:
T extends 't27'
  ? [T]:
T extends 't28'
  ? [T]:
T extends 't29'
  ? [T]:
T extends 't30'
  ? [T]:
T extends 't31'
  ? [T]:
T extends 't32'
  ? [T]:
T extends 't33'
  ? [T]:
T extends 't34'
  ? [T]:
T extends 't35'
  ? [T]:
T extends 't36'
  ? [T]:
T extends 't37'
  ? [T]:
T extends 't38'
  ? [T]:
T extends 't39'
  ? [T]:
T extends 't40'
  ? [T]:
T extends 't41'
  ? [T]:
T extends 't42'
  ? [T]:
T extends 't43'
  ? [T]:
T extends 't44'
  ? [T]:
T extends 't45'
  ? [T]:
T extends 't46'
  ? [T]:
T extends 't47'
  ? [T]: never
)
type PatternArguments2<T extends MessagesKey2> = ( T extends 't48'
  ? [T]:
T extends 't49'
  ? [T]:
T extends 't50'
  ? [T]:
T extends 't51'
  ? [T]:
T extends 't52'
  ? [T]:
T extends 't53'
  ? [T]: never
)
