import dedent from 'dedent-js'

const bannerMessage = (
  '// This file is automatically generated.\n// Please do not change this file!\n\n'
)

const header = dedent`
  import { ComplexPattern } from '@fluent/bundle/esm/ast'
  import { FluentBundle } from '@fluent/bundle'
  
  type Pattern<T> = T | ComplexPattern
  
  type Message<T> = {
    id: T
    value: Pattern<T>
    attributes: Record<string, Pattern<T>>
  }
  
  declare global {
    interface FluentBundleTyped extends FluentBundle {
      getMessage<T extends MessagesKey>(id: T): Message<T>
      formatPattern<T extends MessagesKey>(pattern: Pattern<T>, args?: PatternArguments<T>, errors?: Array<Error> | null): string
    }
  }
`

const buildHeader = () => `${bannerMessage}${header}\n`

export default buildHeader
